try {
    throw new Error('oh no!')
} catch (e){
    console.log(e)
}